name: "TODO-2-gh-issue"
description: "Converts code TODO comments to issues on GitHub. Allows to adjust a few settings to your needs - comment regex, TODO label, GH issue label and others."
author: "Chichuk Dmitrii"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "check-square"
  color: "orange"
